on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read
  packages: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip3 install -r requirements.txt
      
      - uses: rssnyder/ghcr-artifact-store@0.1.0
        with:
          artifact: zines.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - uses: rssnyder/ghcr-artifact-store@0.1.0
        with:
          method: PUT
          artifact: zines.json
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: metrics
        run: echo "last_update{repo=\"$GITHUB_REPOSITORY\",client=\"wilder\"} $(date +%s)" | curl -u metrics:$METRICS_PASSWORD --data-binary @- https://pushmetrics.rileysnyder.org/metrics/job/github_actions/instance/github
        env:
          METRICS_PASSWORD: ${{ secrets.METRICS_PASSWORD }}
